

cinema-city:
  api:
    base-url: https://www.cinema-city.pl/pl/data-api-service/v1/10103/trailers/byCinemaId
    film-details-url: https://www.cinema-city.pl/pl/data-api-service/v1/10103/films/byDistributorCode
    cinema-ids: 1088,1086,1092,1098,1089,1075,1099,1085,1065,1079,1090,1076,1064,1094,1084,1080,1081,1078,1062,1082,1083,1095,1077,1093,1091,1074,1061,1096,1069,1070,1068,1060,1067,1097,1087

screening-fetch:
  date: 2026-01-31  # Format: yyyy-MM-dd