#spring:
#  application:
#    name: cinema-screening-fetcher

cinema:
  fetch:
    cinema-city:
      url: https://www.cinema-city.pl/pl/data-api-service/v1/quickbook/10103/cinemas/with-event/until/2027-01-31?attr=&lang=pl_PL
      provider-id: 1
      enabled: true